<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<!-- ========================================================= -->
	<!-- MODEL VERSION -->
	<!-- ========================================================= -->

	<modelVersion>4.0.0</modelVersion>

	<!-- ========================================================= -->
	<!-- SPRING BOOT PARENT -->
	<!-- ========================================================= -->

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.4</version>
		<relativePath/>
	</parent>

	<!-- ========================================================= -->
	<!-- PROJECT DETAILS -->
	<!-- ========================================================= -->

	<groupId>com.quantity</groupId>
	<artifactId>measurement</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<name>measurement</name>
	<description>Quantity Measurement Application</description>

	<!-- ========================================================= -->
	<!-- JAVA VERSION -->
	<!-- ========================================================= -->

	<properties>
		<java.version>21</java.version>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
	</properties>

	<!-- ========================================================= -->
	<!-- DEPENDENCIES -->
	<!-- ========================================================= -->

	<dependencies>

		<!-- Spring Boot Web MVC -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
		</dependency>

		<!-- H2 DATABASE -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>2.2.224</version>
		</dependency>

		<!-- Spring Boot DevTools -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
		</dependency>

		<!-- Spring Boot Testing -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<!-- ========================================================= -->
	<!-- BUILD -->
	<!-- ========================================================= -->

	<build>

		<plugins>

			<!-- Spring Boot Maven Plugin -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<!-- Maven Compiler Plugin -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>

				<configuration>
					<source>21</source>
					<target>21</target>
				</configuration>
			</plugin>

		</plugins>

	</build>

</project>